kumuluzee:
  name: restaurant-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/RestaurantMetadataDS
      connection-url: jdbc:postgresql://localhost:5431/restaurant-metadata
      username: dbuser
      password: postgres
      pool:
        max-size: 1
  health:
    servlet:
      mapping: /health
      enabled: true
    checks:
      data-source-health-check:
        type: both
        jndi-name: jdbc/RestaurantMetadataDS
      disk-space-health-check:
        type: both
        threshold: 10000000 # 10MB
  metrics:
    web-instrumentation:
      - name: restaurant-endpoint
        url-pattern: /v1/restaurant/*
      - name: health-endpoint
        url-pattern: /health/*
  cors-filter:
    servlet:
      allow-origin: "*"
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                    <Configuration name="restaurant-logging">
                        <Appenders>
                            <Console name="console" target="SYSTEM_OUT">
                                <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                            </Console>
                            <Socket name="logstash" host="90ac9cf8-f6c0-481f-af1b-ee7efd023607-ls.logit.io" port="15163" protocol="udp">
                                <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                            </Socket>
                        </Appenders>
                        <Loggers>
                            <Logger name="si.fri.rso.domen2.restaurant.api.v1.resources.RestaurantMetadataResource" level="trace" additivity="false">
                              <AppenderRef ref="logstash"/>
                            </Logger>
                            <Logger name="si.fri.rso.domen2.restaurant.api.v1.resources.MenusResource" level="trace" additivity="false">
                              <AppenderRef ref="logstash"/>
                            </Logger>
                            <Logger name="si.fri.rso.domen2.restaurant.services.beans.RestaurantMetadataBean" level="trace" additivity="false">
                              <AppenderRef ref="logstash"/>
                            </Logger>
                            <!-- Default logger -->
                            <Root level="all">
                                <AppenderRef ref="console" level="info" />
                            </Root>
                        </Loggers>
                    </Configuration>'
  dev:
    scan-libraries:
      - restaurant-services
      - restaurant-models
      - restaurant-lib

rest-properties:
  maintenance-mode: false
  broken: false

